@startuml
!theme plain

start
:管理员登录系统;
:进入后台管理界面;
:点击食堂管理菜单;
:查看食堂列表\n(分页显示);

if (操作类型?) then (新增)
  :点击新增按钮;
  :弹出编辑对话框;
  :填写食堂信息\n(名称、位置、营业时间);
  :上传食堂图片;
  :点击保存;
  :系统验证数据;
  :保存到数据库;
  :刷新列表;
elseif (编辑)
  :选择食堂点击编辑;
  :修改食堂信息;
  :点击保存;
  :更新数据库;
  :刷新列表;
elseif (删除)
  :选择食堂点击删除;
  if (食堂下有档口?) then (是)
    :提示需先删除档口;
    stop
  else (否)
    :逻辑删除食堂;
    :刷新列表;
  endif
else (档口管理)
  :点击档口管理;
  :选择所属食堂;
  :查看档口列表;
  :新增/编辑/删除档口;
  :保存档口信息;
  :刷新列表;
endif

stop
@enduml